<a href="https://colab.research.google.com/github/tanvi1100/travel-hospitality-data-portfolio/blob/main/Week_2_Traveler_Segmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
users = [
    (1, "Alice", 150, "Business"),
    (2, "Bob", 500, "Luxury"),
    (3, "Charlie", 250, "Leisure"),
    (4, "David", 100, "Budget"),
    (5, "Emma", 700, "Luxury"),
    (6, "Frank", 200, "Leisure")
]

user_df = pd.DataFrame(
    users,
    columns=[
        "user_id",
        "user_name",
        "budget",
        "travel_type"
    ]
)

user_df

   user_id user_name  budget travel_type
0        1     Alice     150    Business
1        2       Bob     500      Luxury
2        3   Charlie     250     Leisure
3        4     David     100      Budget
4        5      Emma     700      Luxury
5        6     Frank     200     Leisure

**Customer Segmentation**

In [3]:
def segment_customer(budget):
    if budget < 200:
        return "Budget"
    elif budget < 500:
        return "Standard"
    else:
        return "Premium"

user_df["segment"] = user_df["budget"].apply(segment_customer)

user_df

   user_id user_name  budget travel_type   segment
0        1     Alice     150    Business    Budget
1        2       Bob     500      Luxury   Premium
2        3   Charlie     250     Leisure  Standard
3        4     David     100      Budget    Budget
4        5      Emma     700      Luxury   Premium
5        6     Frank     200     Leisure  Standard

**Analyze Segments**

In [4]:
user_df["segment"].value_counts()

segment
Budget      2
Premium     2
Standard    2
Name: count, dtype: int64

## Segment Insights

- Budget travelers are price-sensitive.
- Standard travelers seek value and convenience.
- Premium travelers prioritize experience and comfort.

##Hotel Dataset

In [5]:
hotels = [
    ("Budget Comfort", 120),
    ("City Comfort Inn", 180),
    ("Urban Stay", 200),
    ("Ocean View Resort", 320),
    ("Luxury Stay Hotel", 450),
    ("Royal Palace Hotel", 600),
    ("Grand Luxe Hotel", 700)
]

hotel_df = pd.DataFrame(
    hotels,
    columns=["hotel_name", "price"]
)

hotel_df

           hotel_name  price
0      Budget Comfort    120
1    City Comfort Inn    180
2          Urban Stay    200
3   Ocean View Resort    320
4   Luxury Stay Hotel    450
5  Royal Palace Hotel    600
6    Grand Luxe Hotel    700

#Recommendation Logic

In [6]:
def recommend_hotel(budget):
    available = hotel_df[hotel_df["price"] <= budget]

    if len(available) == 0:
        return "No Match"

    return available.sort_values(
        "price",
        ascending=False
    ).iloc[0]["hotel_name"]

user_df["recommended_hotel"] = user_df["budget"].apply(
    recommend_hotel
)

user_df

   user_id user_name  budget travel_type   segment  recommended_hotel
0        1     Alice     150    Business    Budget     Budget Comfort
1        2       Bob     500      Luxury   Premium  Luxury Stay Hotel
2        3   Charlie     250     Leisure  Standard         Urban Stay
3        4     David     100      Budget    Budget           No Match
4        5      Emma     700      Luxury   Premium   Grand Luxe Hotel
5        6     Frank     200     Leisure  Standard         Urban Stay

##Business Interpretation
# Business Insights

- Budget travelers receive affordable hotel recommendations.
- Premium travelers are matched with higher-priced inventory.
- Recommendation logic improves customer experience by aligning hotel options with spending preferences.
- Segmentation can support personalized marketing campaigns and loyalty programs.

## Recommendation Engine Overview

This project segments travelers into Budget, Standard, and Premium groups based on spending preferences and recommends hotels that fit their budgets.

The goal is to simulate how travel platforms can personalize hotel recommendations to improve customer experience and increase booking conversions.

As a Product Analyst, I have evaluated our recent segmentation strategy (Budget, Standard, and Premium) to ensure it aligns with user behavior and business KPIs. Below is a strategic breakdown of our current state and the roadmap for elevating our recommendation logic.
#1. Executive Summary
The implementation of tier-based segmentation marks a shift from a "one-size-fits-all" search result page to a user-centric discovery engine. By grouping travelers into Budget, Standard, and Premium categories based on historical spending and real-time filters, we aim to reduce "choice paralysis" and increase Conversion Rates (CVR).

**Objective:**
Match user price elasticity with inventory to maximize Gross Booking Value (GBV).

**Segment Definitions:**
   **Budget: **High price sensitivity; focuses on utility and location.

   **Standard:** Value-seekers; focus on reviews, amenities, and "star" ratings.

   **Premium:** Experience-driven; low price sensitivity; focuses on luxury, brand prestige, and exclusive services.
##2. Personalization Opportunities
Beyond simple price-matching, we can personalize the user experience (UX) to resonate with the psychology of each segment:

**Budget (The Value Maximizer):**
UI Focus: Highlight "Freebies" (Free Wi-Fi, Breakfast) and "Total Price" transparency.

Content: Show "Deal of the Day" or "Lowest Price in 30 Days" badges to trigger urgency.

Sorting: Default to "Lowest Price" or "Best Value."

**Standard (The Social Proofer):**
UI Focus: Emphasize social proof. Display "X people booked this in the last 24 hours" or "Top Rated for Families."

Content: Comparison modules showing how a "Standard" hotel offers significantly more value than a "Budget" one for a small price delta.

**Premium (The Status Seeker):**

UI Focus: High-resolution, full-screen imagery and minimalist design.

Content: Focus on "VIP Perks" (e.g., room upgrades, late checkout, spa credits). Highlight "Verified Luxury" or "Michelin-star dining on-site."

Sorting: Default to "Guest Rating" or "Exclusivity."
##3. Revenue Optimization Ideas
Segmentation allows us to apply more sophisticated monetization tactics tailored to what each group is willing to pay for:

**Dynamic Ancillary Pricing:**

Budget: Offer low-cost "add-ons" like early check-in or airport shuttles.

Premium: Bundle high-margin services like private city tours or "All-Inclusive" packages into the initial price.

**Tiered Loyalty Incentives:**

Offer Budget travelers "Points" toward future discounts.

Offer Premium travelers "Status" upgrades or access to a dedicated concierge line to build long-term retention.

**Strategic "Upsell" Interstitials:**

When a Standard traveler selects a hotel, show a "Premium" alternative for "Only $40 more per night" to capture the "Treat Yourself" mindset.

**Inventory Rerouting:**

Work with supply partners to offer "Secret Deals" to Budget users for distressed inventory (unsold rooms) that would otherwise remain empty.

##4. Future Improvements for the Recommendation Engine
The goal is to move from **Static Segmentation** to **Predictive Personalization:**

**Contextual Awareness:** The engine should recognize when a "Premium" traveler is booking for business (needs high-speed Wi-Fi, proximity to financial districts) vs. leisure (needs a spa, child-care services).

**Collaborative Filtering (ML):** Move beyond price tiers to "Users like you also booked." If a user frequently stays at boutique lifestyle hotels, the engine should prioritize "vibe" and "design" over just the price category.

**Natural Language Processing (NLP):** Analyze guest reviews to create "Attribute-Based Recommendations." If a user's search history suggests they value "quiet rooms," the engine should boost hotels with high "quietness" scores in the review sentiment analysis.

**Real-time Intent Re-classification:** If a "Budget" traveler starts clicking on 5-star properties, the engine should dynamically shift their segment for that session to capture the potential higher-value booking.

**Predictive Pricing:** Use machine learning to predict when a user's preferred "Standard" hotel is likely to sell out or increase in price, triggering a "Book Now" recommendation.

**Conclusion:**
By moving from a price-centric model to a psychological and behavioral model, we can transform our platform from a transactional tool into a curated travel advisor. This will not only drive immediate conversion but also increase Life Time Value (LTV) through better user satisfaction.

## Key Learning Outcomes

- Built customer segmentation logic using Python and Pandas
- Created a rule-based hotel recommendation engine
- Explored personalization concepts used in travel technology platforms
- Used Google AI Studio to generate product and business insights
- Learned how segmentation can support marketing, pricing, and recommendation strategies